from __future__ import annotations

import argparse
import csv
import json
from pathlib import Path
from typing import Any

from stage_font_probe import stage_font_probe


DEFAULT_FONT = Path("C:/Windows/Fonts/simsun.ttc")
DEFAULT_EXTRACTED_ROOT = Path("local/extracted/Rengoku 2")
DEFAULT_ENTRIES_ROOT = Path("local/work/mcd3_entries")
DEFAULT_SOURCE_ENTRY = Path("local/work/mcd3_entries/DATA001/0017_bin.bin")
TARGET_PAGE = Path("local/work/tdl_DATA001_0002/0011_codeJAP14x14_20_.bin")

CHILD = 11
LOW_BASE = 0x0754
HIGH_BASE = LOW_BASE + 0x51

PROBES = (
    {"cell": 0, "low_code": LOW_BASE + 0, "low_marker": "A", "high_code": HIGH_BASE + 0, "high_marker": "B"},
    {"cell": 1, "low_code": LOW_BASE + 1, "low_marker": "C", "high_code": HIGH_BASE + 1, "high_marker": "D"},
    {"cell": 32, "low_code": LOW_BASE + 32, "low_marker": "E", "high_code": HIGH_BASE + 32, "high_marker": "F"},
    {"cell": 80, "low_code": LOW_BASE + 80, "low_marker": "G", "high_code": HIGH_BASE + 80, "high_marker": "H"},
)


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Build a help-manual probe for the hypothesized child 11 high code window."
    )
    parser.add_argument("--work-root", type=Path, default=Path("local/work/child11_high_base_probe_v1"))
    parser.add_argument("--output-root", type=Path, default=Path("local/rebuilt/child11_high_base_probe_v1_extracted"))
    parser.add_argument("--font", type=Path, default=DEFAULT_FONT)
    parser.add_argument("--font-index", type=int, default=0)
    parser.add_argument("--font-size", type=int, default=12)
    parser.add_argument("--overwrite", action="store_true")
    args = parser.parse_args()

    build_child11_high_probe(
        work_root=args.work_root,
        output_root=args.output_root,
        font_path=args.font,
        font_index=args.font_index,
        font_size=args.font_size,
        overwrite=args.overwrite,
    )
    print(f"staged {args.output_root}")
    return 0


def build_child11_high_probe(
    work_root: Path,
    output_root: Path,
    font_path: Path = DEFAULT_FONT,
    font_index: int = 0,
    font_size: int = 12,
    overwrite: bool = False,
) -> None:
    work_root.mkdir(parents=True, exist_ok=True)
    text_json = work_root / "DATA001_0017_child11_high_probe.json"
    text_json.write_text(json.dumps(build_text_payload(), ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

    write_probe_manifest(work_root / "probe_manifest.csv")
    write_readme(work_root / "README.md", output_root)

    stage_config = {
        "extracted_root": str(DEFAULT_EXTRACTED_ROOT),
        "entries_root": str(DEFAULT_ENTRIES_ROOT),
        "work_root": str(work_root / "stage"),
        "output_root": str(output_root),
        "font_patches": build_font_patches(work_root / "previews", font_path, font_index, font_size),
        "text_patches": [
            {
                "entry_id": 17,
                "source_entry": str(DEFAULT_SOURCE_ENTRY),
                "json": str(text_json),
            }
        ],
        "overwrite": overwrite,
    }
    (work_root / "stage_child11_high_probe.json").write_text(
        json.dumps(stage_config, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    stage_font_probe(stage_config)


def build_text_payload() -> dict[str, Any]:
    lines = [
        "C11 LOW/HIGH PROBE",
        "0754=A 07A5=B",
        "0755=C 07A6=D",
        "0774=E 07C5=F",
        "07A4=G 07F5=H",
    ]
    entries = [
        {
            "id": "child11-high-probe-title",
            "record": 11,
            "run": 0,
            "kind": "text",
            "length": 10,
            "text": "",
            "translation": "C11 PROBE",
            "notes": "A > 1 manual title marker.",
        },
        {
            "id": "child11-high-probe-body",
            "record": 12,
            "run": 0,
            "kind": "glyph_codes",
            "length": 215,
            "translation": "",
            "translation_codes": [f"0x{code:04x}" for code in encode_probe_body(lines)],
            "notes": "A > 1 manual body marker; generated by tools/build_child11_high_probe.py.",
        },
    ]
    return {
        "format": "offset-table-runs-v1",
        "source": str(DEFAULT_SOURCE_ENTRY),
        "entries": entries,
    }


def encode_probe_body(lines: list[str]) -> list[int]:
    codes: list[int] = []
    marker_by_code = {
        int(probe["low_code"]): str(probe["low_marker"])
        for probe in PROBES
    } | {
        int(probe["high_code"]): str(probe["high_marker"])
        for probe in PROBES
    }
    for line_index, line in enumerate(lines):
        cursor = 0
        while cursor < len(line):
            matched_code = next(
                (code for code in marker_by_code if line.startswith(f"{code:04X}=", cursor)),
                None,
            )
            if matched_code is None:
                codes.append(ord(line[cursor]))
                cursor += 1
                continue
            label = f"{matched_code:04X}="
            codes.extend(ord(char) for char in label)
            codes.append(matched_code)
            cursor += len(label) + 1
        if line_index != len(lines) - 1:
            codes.append(0x000A)
    return codes


def build_font_patches(
    preview_dir: Path,
    font_path: Path,
    font_index: int,
    font_size: int,
) -> list[dict[str, Any]]:
    patches = []
    for probe in PROBES:
        cell = int(probe["cell"])
        for layer, marker in (("low", probe["low_marker"]), ("high", probe["high_marker"])):
            patches.append(
                {
                    "mode": "render_bitplane",
                    "target_page": str(TARGET_PAGE),
                    "target_child": CHILD,
                    "target_cell": cell,
                    "layer": layer,
                    "char": marker,
                    "font": str(font_path),
                    "font_index": font_index,
                    "font_size": font_size,
                    "render_mode": "binary",
                    "threshold": 64,
                    "gray_threshold": 176,
                    "stroke_radius": 0,
                    "preview": str(preview_dir / f"child11_cell{cell:02d}_{layer}_{marker}.png"),
                    "source": TARGET_PAGE.stem,
                }
            )
    return patches


def write_probe_manifest(path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as file:
        writer = csv.DictWriter(
            file,
            fieldnames=["child", "source", "cell", "layer", "display_code", "marker", "expected"],
        )
        writer.writeheader()
        for probe in PROBES:
            for layer, code_key, marker_key in (
                ("low", "low_code", "low_marker"),
                ("high", "high_code", "high_marker"),
            ):
                writer.writerow(
                    {
                        "child": CHILD,
                        "source": TARGET_PAGE.stem,
                        "cell": probe["cell"],
                        "layer": layer,
                        "display_code": f"0x{int(probe[code_key]):04x}",
                        "marker": probe[marker_key],
                        "expected": f"{int(probe[code_key]):04X}={probe[marker_key]}",
                    }
                )


def write_readme(path: Path, output_root: Path) -> None:
    expected = []
    for probe in PROBES:
        expected.append(
            f"- cell {probe['cell']:02d}: `{probe['low_code']:04X}={probe['low_marker']}` "
            f"and `{probe['high_code']:04X}={probe['high_marker']}`"
        )
    lines = [
        "# Child 11 High-Base Probe v1",
        "",
        f"PPSSPP-ready artifact: `{output_root.as_posix()}/`",
        "",
        "Open help/manual `A > 1`. The page title is changed to `C11 PROBE`",
        "and the body displays four low/high code pairs from child 11.",
        "",
        "Hypothesis under test:",
        "",
        "- child 11 low base: `0x0754`",
        "- child 11 high base: `0x07a5` (`0x0754 + 0x51`)",
        "",
        "Expected visible markers:",
        "",
        *expected,
        "",
        "If the right side of each pair shows B/D/F/H, child 11 follows the",
        "same high-base rule as the other confirmed pages. If those slots are",
        "blank, wrong, or aliases of A/C/E/G, the child 11 high route still",
        "needs a separate model.",
        "",
        "Read `probe_manifest.csv` for the exact child/cell/layer mapping.",
    ]
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


if __name__ == "__main__":
    raise SystemExit(main())
